version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: pOstgr3s@2023
      POSTGRES_DB: ecommerce
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  postgres_data:
