version: '3.9'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: pOstgr3s@2023
      POSTGRES_DB: ecommerce
    ports:
      - 5432:5432
