import { Checkout } from "./application/Checkout";
import { GetOrdersByCpf } from "./application/GetOrdersByCpf";
import { Preview } from "./application/Preview";
import { Item } from "./domain/entities/Item";
import { OrderController } from "./infra/controllers/OrderController";
import { ExpressAdapter } from "./infra/http/ExpressAdapter";
import { ItemRepositoryMemory } from "./infra/repositories/memory/ItemRepositoryMemory";
import { OrderRepositoryMemory } from "./infra/repositories/memory/OrderRepositoryMemory";

const itemRepository = new ItemRepositoryMemory();
itemRepository.save(new Item(1, "Camiseta", 50));
itemRepository.save(new Item(2, "Caneca", 15));
itemRepository.save(new Item(3, "Poster", 30));
const orderRepository = new OrderRepositoryMemory();
const preview = new Preview(itemRepository);
const checkout = new Checkout(itemRepository, orderRepository);
const getOrdersByCpf = new GetOrdersByCpf(orderRepository);
const httpServer = new ExpressAdapter();
new OrderController(httpServer, preview, checkout, getOrdersByCpf);
httpServer.listen(3333);
